# Generated by Django 3.1.6 on 2021-02-08 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClassFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=500)),
                ('short_description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RaceFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('short_description', models.TextField(max_length=200)),
                ('modifies', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=500)),
                ('short_description', models.TextField(max_length=200)),
                ('first_feature_name', models.CharField(max_length=20)),
                ('first_description', models.TextField(max_length=500)),
                ('first_short_description', models.TextField(max_length=200)),
                ('second_feature_name', models.CharField(max_length=20)),
                ('second_description', models.TextField(max_length=500)),
                ('second_short_description', models.TextField(max_length=200)),
                ('third_feature_name', models.CharField(max_length=20)),
                ('third_description', models.TextField(max_length=500)),
                ('third_short_description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('level', models.IntegerField(default=1)),
                ('hit_dice', models.IntegerField(default=8)),
                ('features', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.classfeature')),
                ('skill_proficiencies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=500)),
                ('ability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.ability')),
                ('pokemon_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.pokemontype')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=500)),
                ('ability_bonus_name', models.CharField(max_length=20)),
                ('languages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.language')),
                ('race_feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.racefeature')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=500)),
                ('classification', models.CharField(max_length=30)),
                ('specie_rating', models.CharField(max_length=5)),
                ('evolution_description', models.TextField(max_length=500)),
                ('ability_saving_throws', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.ability')),
                ('egg_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egg_type', to='main_app.pokemontype')),
                ('pokemon_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.pokemontype')),
                ('proficient_skills', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.skill')),
                ('resistance_types', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resistant_type', to='main_app.pokemontype')),
                ('starting_moves', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.move')),
                ('vulnerability_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerable_type', to='main_app.pokemontype')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('alignment', models.CharField(max_length=20)),
                ('lifestyle', models.CharField(max_length=60)),
                ('hair', models.TextField(max_length=300)),
                ('skin', models.TextField(max_length=300)),
                ('eyes', models.TextField(max_length=300)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=30)),
                ('notes', models.TextField(max_length=1000)),
                ('features', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.classfeature')),
                ('items', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.characteritem')),
                ('path', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.trainerpath')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.race')),
                ('skill_proficiencies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.skill')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.specialization')),
                ('starter_pokemon', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.pokemon')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.character'),
        ),
    ]
