# Generated by Django 3.1.6 on 2021-02-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210209_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='evolution_description',
            field=models.TextField(max_length=600),
        ),
    ]
