# Generated by Django 3.1.6 on 2021-02-09 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210209_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='features',
        ),
        migrations.RemoveField(
            model_name='character',
            name='items',
        ),
        migrations.RemoveField(
            model_name='character',
            name='path',
        ),
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
        migrations.RemoveField(
            model_name='character',
            name='skill_proficiencies',
        ),
        migrations.RemoveField(
            model_name='character',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='character',
            name='starter_pokemon',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='character',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='ability_saving_throws',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='egg_group',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='pokemon_type',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='proficient_skills',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='resistance_types',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='starting_moves',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='vulnerability_type',
        ),
        migrations.RemoveField(
            model_name='race',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='race',
            name='race_feature',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='ability',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='pokemon_type',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='trainerclass',
            name='features',
        ),
        migrations.RemoveField(
            model_name='trainerclass',
            name='skill_proficiencies',
        ),
        migrations.AddField(
            model_name='ability',
            name='pokemon_saving_throws',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.pokemon'),
        ),
        migrations.AddField(
            model_name='ability',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.specialization'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='characteritem',
            name='character',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.character'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classfeature',
            name='character_class_features',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.character'),
        ),
        migrations.AddField(
            model_name='classfeature',
            name='trainer_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.trainerclass'),
        ),
        migrations.AddField(
            model_name='language',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.race'),
        ),
        migrations.AddField(
            model_name='move',
            name='pokemon_starting_moves',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.pokemon'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='character',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.character'),
        ),
        migrations.AddField(
            model_name='pokemonability',
            name='pokemon_abilities',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.pokemon'),
        ),
        migrations.AddField(
            model_name='pokemontype',
            name='pokemon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.pokemon'),
        ),
        migrations.AddField(
            model_name='pokemontype',
            name='pokemon_resistance_types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resistant_types', to='main_app.pokemon'),
        ),
        migrations.AddField(
            model_name='pokemontype',
            name='pokemon_vulnerability_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vulnerable_types', to='main_app.pokemon'),
        ),
        migrations.AddField(
            model_name='race',
            name='character_race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.character'),
        ),
        migrations.AddField(
            model_name='racefeature',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.race'),
        ),
        migrations.AddField(
            model_name='skill',
            name='character_proficiencies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.character'),
        ),
        migrations.AddField(
            model_name='skill',
            name='class_proficiencies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.trainerclass'),
        ),
        migrations.AddField(
            model_name='skill',
            name='pokemon_proficiencies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.pokemon'),
        ),
        migrations.AddField(
            model_name='skill',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.specialization'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.character'),
        ),
        migrations.AddField(
            model_name='trainerpath',
            name='character',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.character'),
        ),
        migrations.CreateModel(
            name='EggGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pokemon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.pokemon')),
            ],
        ),
    ]
