# Generated by Django 3.1.6 on 2021-02-09 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210209_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='pokemon_saving_throws',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='character',
            name='max_specie_rating',
        ),
        migrations.RemoveField(
            model_name='character',
            name='pokeslots',
        ),
        migrations.RemoveField(
            model_name='character',
            name='proficiency_bonus',
        ),
        migrations.RemoveField(
            model_name='characteritem',
            name='character',
        ),
        migrations.RemoveField(
            model_name='classfeature',
            name='character_class_features',
        ),
        migrations.RemoveField(
            model_name='egggroup',
            name='pokemon',
        ),
        migrations.RemoveField(
            model_name='language',
            name='race',
        ),
        migrations.RemoveField(
            model_name='move',
            name='pokemon_starting_moves',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='character',
        ),
        migrations.RemoveField(
            model_name='pokemonability',
            name='pokemon_abilities',
        ),
        migrations.RemoveField(
            model_name='pokemontype',
            name='pokemon',
        ),
        migrations.RemoveField(
            model_name='pokemontype',
            name='pokemon_resistance_types',
        ),
        migrations.RemoveField(
            model_name='pokemontype',
            name='pokemon_vulnerability_type',
        ),
        migrations.RemoveField(
            model_name='race',
            name='character_race',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='character_proficiencies',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='class_proficiencies',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='pokemon_proficiencies',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='character',
        ),
        migrations.RemoveField(
            model_name='trainerpath',
            name='character',
        ),
        migrations.AddField(
            model_name='character',
            name='items',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_app.characteritem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.trainerpath'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.race'),
        ),
        migrations.AddField(
            model_name='character',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.specialization'),
        ),
        migrations.AddField(
            model_name='character',
            name='starter_pokemon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.pokemon'),
        ),
        migrations.AddField(
            model_name='character',
            name='trainer_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.trainerclass'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ability_saving_throws',
            field=models.ManyToManyField(null=True, to='main_app.Ability'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='egg_group',
            field=models.ManyToManyField(null=True, related_name='egg_type', to='main_app.PokemonType'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_type',
            field=models.ManyToManyField(null=True, to='main_app.PokemonType'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='proficient_skills',
            field=models.ManyToManyField(null=True, to='main_app.Skill'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='resistance_types',
            field=models.ManyToManyField(null=True, related_name='resistant_type', to='main_app.PokemonType'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='starting_moves',
            field=models.ManyToManyField(null=True, to='main_app.Move'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='vulnerability_type',
            field=models.ManyToManyField(null=True, related_name='vulnerable_type', to='main_app.PokemonType'),
        ),
        migrations.AddField(
            model_name='race',
            name='languages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.language'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='ability',
            field=models.ManyToManyField(null=True, to='main_app.Ability'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='pokemon_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.pokemontype'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='skill',
            field=models.ManyToManyField(null=True, to='main_app.Skill'),
        ),
        migrations.AddField(
            model_name='trainerclass',
            name='skill_proficiencies',
            field=models.ManyToManyField(null=True, to='main_app.Skill'),
        ),
    ]
