# Generated by Django 3.1.6 on 2021-02-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210209_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='ability_saving_throws',
            field=models.ManyToManyField(to='main_app.Ability'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='egg_group',
            field=models.ManyToManyField(to='main_app.EggGroup'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_type',
            field=models.ManyToManyField(to='main_app.PokemonType'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='proficient_skills',
            field=models.ManyToManyField(to='main_app.Skill'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='resistance_types',
            field=models.ManyToManyField(related_name='resistant_type', to='main_app.PokemonType'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='starting_moves',
            field=models.ManyToManyField(to='main_app.Move'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='vulnerability_type',
            field=models.ManyToManyField(related_name='vulnerable_type', to='main_app.PokemonType'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='ability',
            field=models.ManyToManyField(to='main_app.Ability'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='skill',
            field=models.ManyToManyField(to='main_app.Skill'),
        ),
        migrations.AlterField(
            model_name='trainerclass',
            name='skill_proficiencies',
            field=models.ManyToManyField(to='main_app.Skill'),
        ),
    ]
