# Generated by Django 3.1.6 on 2021-02-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20210209_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='items',
        ),
        migrations.AddField(
            model_name='character',
            name='pack',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='pokeballs',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='pokedex',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='pokedollars',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='potions',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='trainer_license',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CharacterItem',
        ),
    ]
