# Generated by Django 3.1.6 on 2021-02-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210210_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'ordering': ['name']},
        ),
    ]
