# Generated by Django 3.1.6 on 2021-02-10 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210210_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classfeature',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='egggroup',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='move',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='pokemontype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='racefeature',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
    ]
