# Generated by Django 3.1.6 on 2021-02-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210210_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='skill_one',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='skill_two',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
