# Generated by Django 3.1.6 on 2021-02-11 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210211_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='skill_one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_one', to='main_app.skill'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skill_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_two', to='main_app.skill'),
        ),
    ]
