# Generated by Django 3.1.6 on 2021-02-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20210211_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='alignment',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='eyes',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='character',
            name='height',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='lifestyle',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='character',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='character',
            name='skin',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='character',
            name='weight',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
